name: Main Pipeline - Build, Test & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  # JOB: Build Docker Production Image
  build-production:
    runs-on: ubuntu-latest
    name: Build Production Image
    if: github.ref == 'refs/heads/production'  # Only for production branch
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Production Docker Image
      run: docker build -f Dockerfile -t snc:${{ github.sha }} .
    
    - name: Push to Container Registry
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker tag snc:${{ github.sha }} vecalciskay/snc:${{ github.sha }}
        docker tag snc:${{ github.sha }} vecalciskay/snc:latest
        docker push vecalciskay/snc:${{ github.sha }}
        docker push vecalciskay/snc:latest
